### ISSUE TITLE
Error in "OpenSAMM_Assessment_Toolbox_v1-1-Final" doc, in "Roadmap Chart" tab due to regional decimal settings

### ISSUE THREAD

**Issue by josegoose** [OWASP/opensamm#2]
Error in "OpenSAMM_Assessment_Toolbox_v1-1-Final" doc, in "Roadmap Chart" tab due to local decimal settings

**WHERE**
In the document https://github.com/OWASP/opensamm/blob/master/v1.1/Final/OpenSAMM_Assessment_Toolbox_v1-1-Final.xlsx in the tab "Roadpmap Chart" in the cells "B10:B21"

**WHAT**
The "Start" value is showing an error, when the security practice score contains the character "+" and the regional settings have the decimal symbol set to comma ","

![image](https://cloud.githubusercontent.com/assets/2046534/16271964/494426b2-389c-11e6-8096-394816b5e514.png)

**HOW TO RECREATE**
[Recreated on Windows 8.1 and Excel 2016]

1. Go to Windows Control Panel -> Clock, Language and Region -> Region
2. Click on "Additional settings..." button
3. Set decimal symbol to ",". Click "Ok" button. Click "Ok" button again.
4. In the Excel document, go to "Interview" tab
5. Set the value "Yes" in cell: E18, 
6. Set the value "No" in cells: E23, E28, E35, E41, E44, E48 and E56. (The cell I18 must be set to value "0+")
7. Go to "Roadmap Chart" tab

ERROR: The cell B10 is showing the error message "#VALUE!"
EXPECTED: The cell B10 must show the value "0,5"

**SUGGESTED FIX**
Fix the formula on the cells B10:B21 replacing the ".5" by 1/2.

Example to fix cell B10:
Replace
![image](https://cloud.githubusercontent.com/assets/2046534/16272515/5345fc7e-389e-11e6-9e98-588422cfec98.png)
by
![image](https://cloud.githubusercontent.com/assets/2046534/16272487/3ef6e076-389e-11e6-927f-ce9e4968cd63.png)

**Comment by SebaDele** [comment]
fixed in v1.1.1

**Comment by josegoose** [comment]
Thanks!
